---
- name: Ensure that the {{ hermes_package }} package is installed
  tags: hermes
  homebrew_cask:
    name: "{{ hermes_package|lower }}"
    state: present
  register: hermes_homebrew_cask

- name: Attempting to apply {{ hermes_package }} configurations
  tags: hermes
  osx_defaults:
    domain: "{{ hermes_domain }}"
    key: "{{ item.key|regex_replace('_', ' ') }}"
    state: "{{ item.value.state|default('present') }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ hermes_defaults }}"
  when:
    - item.key is defined
    - item.value.type is defined
    - item.value.value is defined
    - hermes_defaults|length > 0
    - hermes_homebrew_cask is success
...
