---
- name: Ensure that the {{ hermes_package }} package is installed
  tags: hermes
  homebrew_cask:
    name: "{{ hermes_package|lower }}"
    state: present
  when: hermes_package|length > 0

- name: Attempting to apply {{ hermes_package }} configurations
  tags: hermes
  osx_defaults:
    domain: "{{ hermes_domain }}"
    key: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ hermes_defaults }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - item.type is defined
    - item.value is defined
    - hermes_defaults|length > 0
    - hermes_domain is defined
...
